before_script:
  - echo 'memory_limit = 2048M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
  - export APP_ENV=test

stages:
  - prepare
  - lint
  - test

dependency:
  stage: prepare
  image:  gitlab.webchili.in:4567/docker-images/php-dev:7.4
  cache:
    key: code-cache-1-0-0
    paths:
      - vendor
      - public
  script:
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - export COMPOSER_HOME=/root/.composer
    - echo "$COMPOSER_CONFIGJSON" > /root/.composer/config.json
    - export COMPOSER_AUTH=$COMPOSER_AUTHJSON
    - composer install --no-scripts --prefer-dist
    - composer clear-cache
  tags:
    - php

tests:
  stage: test
  image:  gitlab.webchili.in:4567/docker-images/php-dev:7.4
  cache:
    key: code-cache-1-0-0
    paths:
      - vendor
    policy: pull
  script:
    - composer test-coverage-ci
  artifacts:
    when: always
    paths:
      - Test/var/log
    reports:
      junit: phpunit_report.xml
    expire_in: 1 day
  tags:
    - php

code_style:
  stage: lint
  image:  gitlab.webchili.in:4567/docker-images/php-dev:7.4
  cache:
    key: code-cache-1-0-0
    paths:
      - vendor
    policy: pull
  script:
    - composer style
  tags:
    - php

code_quality:
  stage: lint
  image:  gitlab.webchili.in:4567/docker-images/php-dev:7.4
  cache:
    key: code-cache-1-0-0
    paths:
      - vendor
    policy: pull
  script:
    - composer quality
  #    - composer quality-ci
  #  after_script:
  #    - cat quality-report.json | grep -v -e '^$' > quality-report2.json
  #  artifacts:
  #    when: always
  #    expire_in: 1 month
  #    paths:
  #      - quality-report.json
  #      - quality-report2.json
  #    reports:
  #      codequality: quality-report2.json
  tags:
    - php
