services:
  php:
    build:
      context: .
      target: whisky_dev
    volumes:
      - ./:/srv/app
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "client_port=9003 client_host=host.docker.internal idekey=PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
