name: Quality

on:
  push:
    branches: [ 1.0 ]
  pull_request:
    branches: [ 1.0 ]

jobs:
  build:

    runs-on: ubuntu-20.04
    name: Quality & Test
    strategy:
      fail-fast: false
      matrix:
        include:
          -   php: "8.1"

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: "matrix.php == '8.1' && ! matrix.mode"
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run check-all
      if: "matrix.php == '8.1' && ! matrix.mode"
      run: composer run-script check-all
